services:
  db:
    image: "mysql:8.0.37"
    environment:
      MYSQL_DATABASE: hbnb_evo_db
      MYSQL_USER: hbnb_evo
      MYSQL_PASSWORD: hbnb_evo_pwd
      MYSQL_ROOT_PASSWORD: password
    container_name: "hbnb_evo_2_db"
    restart: always
    ports:
      - "3306:3306"
    networks:
      - private
  server:
    image: "ubuntu:latest"
    environment:
      IS_DOCKER_CONTAINER: 1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "hbnb_evo_2_server"
    restart: always
    ports:
      - "5000:5000"
    networks:
      - private
    depends_on:
      - db

networks:
  private:
